In [1]:
import pandas as pd

In [2]:
batch_1 = pd.read_csv('../data/2013_data_batch_1.csv')
batch_2 = pd.read_csv('../data/2013_data_batch_2.csv')
batch_3 = pd.read_csv('../data/2013_data_batch_3.csv')
batch_4 = pd.read_csv('../data/2013_data_batch_4.csv')

In [3]:
len(batch_1)

999

In [4]:
len(batch_2)

978

In [5]:
len(batch_3)

979

In [6]:
len(batch_4)

401

In [7]:
df = pd.DataFrame()

In [8]:
df = pd.concat([batch_1, batch_2, batch_3, batch_4], ignore_index=True)

In [9]:
len(df)

3357

In [10]:
df.head(100)

,title_id,title,box_office,country,genre,director,metascore,production,rating,IMDB_rating,rotten_tomatoes_rating,runtime,type,IMDB_votes
0,tt4470336,#50Fathers,NaN,USA,Comedy,Joddy Eric Matthews,NaN,NaN,NaN,NaN,NaN,132 min,movie,NaN
1,tt5460468,#Enough,NaN,USA,Drama,Miranda Ferguson,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
2,tt3526286,#Horror,NaN,USA,"Crime, Drama, Horror, Mystery, Thriller",Tara Subkoff,42.0,NaN,Not Rated,3.0,NaN,101 min,movie,"3,218"
3,tt2538204,#Lucky Number,NaN,USA,Comedy,Brendan Gabriel Murphy,NaN,NaN,TV-14,5.0,NaN,80 min,movie,435
4,tt5466780,#Standards,NaN,USA,Drama,Melanie Page,NaN,NaN,NaN,NaN,NaN,50 min,movie,NaN
5,tt4444974,#blessed,NaN,USA,"Documentary, Comedy","Rich Costales, Kailee McGee",NaN,NaN,NaN,NaN,NaN,83 min,movie,NaN
6,tt4397606,$kumbagz,NaN,USA,"Crime, Thriller",John Miller,NaN,NaN,NaN,7.6,NaN,71 min,movie,9
7,tt3234822,We Should Have This Conversation After Dinner,NaN,USA,Comedy,Nine Blackmon,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
8,tt3556238,'Tis the Season,NaN,USA,Comedy,"Kevin Burge, Tad Sisler",NaN,"Main Road Productions, LTD.",NaN,NaN,NaN,NaN,movie,NaN
9,tt4872362,(313) Choices,NaN,USA,Drama,"Tyler Clifton, Brock Lewandowski, Sarah R. Mat...",NaN,NaN,NaN,NaN,NaN,90 min,movie,NaN
10,tt7122468,1 Chisper,NaN,USA,Horror,Jaume Collet-Serra,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
11,tt4152210,1 world 100 lonely,NaN,USA,"Comedy, Drama, Romance",Brian McGuire,NaN,NaN,NaN,NaN,NaN,116 min,movie,NaN
12,tt4418268,1.7 Alpha,NaN,USA,"Drama, Sci-Fi",Quanah Jay Hicks,NaN,NaN,NaN,7.4,NaN,97 min,movie,14
13,tt5282238,10,NaN,USA,Thriller,Jeff Morris,NaN,NaN,NaN,4.7,NaN,90 min,movie,7
14,tt3453052,10 Days in a Madhouse,NaN,USA,Drama,Timothy Hines,NaN,NaN,R,6.7,NaN,111 min,movie,"1,165"
15,tt4562630,10 Minutes,NaN,USA,"Action, Drama, Thriller",Saquan Jones,NaN,NaN,NaN,NaN,NaN,67 min,movie,NaN
16,tt3397754,Ten Thousand Saints,NaN,USA,"Comedy, Drama, Music","Shari Springer Berman, Robert Pulcini",62.0,Screen Media Ventures,R,5.9,58%,113 min,movie,"5,028"
17,tt5116930,1000 Waves to Surfing Glory: Pop up Edition,NaN,USA,NaN,Josh Pomer,NaN,NaN,G,NaN,NaN,49 min,movie,NaN
18,tt3219396,101 Secrets,NaN,USA,"Adventure, Drama, Fantasy",Tophy Cho,NaN,NaN,NaN,6.2,NaN,95 min,movie,6
19,tt3957956,12 Rounds 3: Lockdown,NaN,USA,"Action, Crime, Thriller",Stephen Reynolds,NaN,Lionsgate Films,R,5.2,NaN,90 min,movie,"3,433"
20,tt7096318,12th Night,NaN,USA,NaN,Micah Thompson,NaN,NaN,NaN,NaN,NaN,80 min,movie,NaN
21,tt3781762,1915,NaN,USA,Drama,"Garin Hovannisian, Alec Mouhibian",NaN,Bloodvine Media,NaN,4.3,40%,82 min,movie,"4,462"
22,tt5085766,1:31 Am,NaN,USA,"Adventure, Drama, Sci-Fi",Stefan Kristinkov,NaN,NaN,NaN,NaN,NaN,94 min,movie,NaN
23,tt3798912,1st Date,NaN,USA,"Comedy, Romance","James Huang, Elizabeth Sandy",NaN,NaN,NaN,4.0,NaN,89 min,movie,9
24,tt4926610,2014 Gold Rush Expedition Race,NaN,USA,Sport,Brian J. Leitten,NaN,NaN,NaN,NaN,NaN,66 min,movie,NaN
25,tt6361988,2015 Dancing Dolls a Christmas Story,NaN,USA,Family,Charon Aldredge,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
26,tt4423458,"2053 More Girls, a Dragon & a Fisherman",NaN,USA,NaN,Gary Davis,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
27,tt4460384,2053 Viejo the Black Samurai,NaN,USA,NaN,Gary Davis,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
28,tt4714278,21st Century Spectacle,NaN,USA,"Comedy, Fantasy",Angeline Walsh,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
29,tt3515632,SWAT: Unit 887,NaN,USA,"Action, Thriller",Timothy Woodward Jr.,NaN,NaN,Not Rated,3.0,NaN,96 min,movie,593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,tt5341454,A Broken Ladder,NaN,USA,"Crime, Drama, Mystery",NaN,NaN,NaN,NaN,NaN,NaN,96 min,movie,NaN
71,tt4456158,Did You Know...,NaN,NaN,Comedy,Rick Mowat,NaN,NaN,NaN,NaN,NaN,90 min,movie,NaN
72,tt3085778,A Choice to Yield,NaN,USA,"Comedy, Drama, Romance","Jonathan W. Hickman, Bobby Peoples, Renee S. W...",NaN,NaN,NaN,NaN,NaN,90 min,movie,NaN
73,tt4776578,A Christmas Carol,NaN,"Canada, USA","Drama, Family, Fantasy, Musical",Anthony D.P. Mann,NaN,NaN,Not Rated,3.8,NaN,59 min,movie,47
74,tt7709408,A Christmas Carol in San Miguel de Allende,NaN,USA,NaN,Chuck Rubin,NaN,NaN,NaN,NaN,NaN,90 min,movie,NaN
75,tt5325762,"A Christmas Carol, 50th Anniversary",NaN,USA,"Drama, Family, Musical",Tim Dietlein,NaN,NaN,NaN,NaN,NaN,118 min,movie,NaN
76,tt4690134,A Christmas Eve Miracle,NaN,USA,"Comedy, Family",R. Michael Givens,NaN,SP Worldwide,Not Rated,3.5,NaN,80 min,movie,209
77,tt4067684,A Christmas to Remember,NaN,USA,"Comedy, Drama, Family",Henderson Maddox,NaN,ACTR Productions,Not Rated,5.4,NaN,112 min,movie,35
78,tt3373586,A City to Make Me,NaN,USA,Sci-Fi,Ryan Miller,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
79,tt3731618,A Clear View the Mark Barmore Story,NaN,USA,Drama,John Dawson,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
80,tt3894386,A Close Divide,NaN,USA,Sci-Fi,Jesse Alexander,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
81,tt5312338,A Cold Day in Hell,NaN,USA,Drama,Nickolas Robison,NaN,NaN,NaN,NaN,NaN,72 min,movie,NaN
82,tt3953626,A Country Called Home,NaN,USA,Drama,Anna Axster,46.0,NaN,NOT RATED,5.9,NaN,90 min,movie,893
83,tt4280250,A Date to Die For,NaN,USA,Thriller,John Murlowski,NaN,ADTDF Utah Productions,TV-14,5.3,NaN,86 min,movie,124
84,tt4587676,A Day in the Life of a Mobster,NaN,USA,Drama,Emily Kathleen,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
85,tt4984896,A Day with God,NaN,USA,"Short, Drama",Arshum Rouhanian,NaN,NaN,NaN,NaN,NaN,54 min,movie,NaN
86,tt5112490,A Dionysia,NaN,USA,Music,Timothy J. Armstrong,NaN,NaN,NaN,NaN,NaN,59 min,movie,NaN
87,tt2278803,A Dog for Christmas,NaN,USA,"Comedy, Family",NaN,NaN,NaN,NaN,6.4,NaN,89 min,movie,19
88,tt3991066,A Dogwalker's Christmas Tale,NaN,USA,"Comedy, Drama, Family, Romance",Letia Clouston,NaN,G It&#39;s Entertainment,TV-G,5.1,NaN,86 min,movie,"1,128"
89,tt2898832,A Dungeon Master's Guide to Life,NaN,USA,"Comedy, Drama",Chris Bruemmer,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
90,tt3131266,A Fatal Friend,NaN,USA,Thriller,Eric Darnell Redding,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
91,tt3187094,A Fatal Obsession,NaN,USA,Thriller,James Camali,NaN,Switzer Entertainment Group,TV-14,4.4,NaN,86 min,movie,147
92,tt3577328,A Father's Journey,NaN,USA,Drama,David Fernandez Jr.,NaN,NaN,NaN,9.4,NaN,87 min,movie,48
93,tt2699466,A Fighting Season,NaN,USA,"Drama, News, War",Oden Roberts,NaN,NaN,NaN,7.4,NaN,82 min,movie,42
94,tt3764048,A Final Hit,NaN,USA,"Action, Drama",RJ Cusyk,NaN,NaN,NOT RATED,6.4,NaN,82 min,movie,11
95,tt3247646,A Ghost and the Boy with A Box on His Head,NaN,USA,"Adventure, Drama",Philip Blue,NaN,NaN,NaN,NaN,NaN,73 min,movie,NaN
96,tt3954294,A Gift Horse,NaN,USA,Family,Teddy Smith,NaN,Leverage Entertainment,TV-G,5.1,NaN,83 min,movie,141
97,tt3507138,A Girl Like Grace,NaN,USA,Drama,Ty Hodges,NaN,GVN Releasing,PG-13,5.9,NaN,93 min,movie,429
98,tt2523832,A Girl Like Her,NaN,USA,Drama,Amy S. Weber,54.0,Parkside Releasing,PG-13,7.0,65%,91 min,movie,"6,502"
99,tt4991434,A Harlequin in Darkness,NaN,USA,Thriller,Michael Mason,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN

In [11]:
total = len(df.country.unique())
unique = df.country.unique()
for i in range (total):
    print(unique[i])

USA
Iran, USA
Mexico, USA
Canada, USA
Australia, Guyana, USA
nan
Australia, Canada, USA
Israel, USA
Canada, USA, India, Vietnam
USA, Italy
Romania, USA, Ukraine
China, USA
USA, UK
UK, USA
Italy, Spain, USA, UK, Sweden
USA, Bosnia and Herzegovina, Croatia, Italy, Switzerland
Peru, USA
USA, Canada
USA, Hong Kong
Guatemala, USA
Germany, USA
Switzerland, USA
France, USA
France
Germany, Ukraine, USA
Spain, USA
USA, France, Germany
Taiwan, USA
USA, Colombia
USA, Trinidad and Tobago
China, UK, USA
USA, Cameroon
USA, Mexico
Hungary, USA, Russia, Romania
USA, Dominican Republic
India, Hong Kong, Indonesia, Philippines, Singapore, USA, United Arab Emirates
USA, France, Belgium
United Arab Emirates, USA, Switzerland
Australia, USA
USA, France
Cyprus, Greece, USA, Serbia
Lebanon, USA
Germany, India, USA
India, USA
Czech Republic, USA
France, Malta, USA
USA, UK, Spain, Italy, France
Albania, USA
South Africa, USA
Hong Kong, China, USA
Czech Republic, UK, USA, Russia
USA, Germany, Brazil
UK, Australia, USA
South Korea, Thailand, USA
USA, UK, France
Netherlands, USA
New Zealand, USA
Germany, USA, South Africa, Norway, Italy, Hong Kong, Brazil, Australia
USA, Turkey, Italy, India
Germany
Mexico, India, USA, Argentina, Spain
USA, Cambodia
Italy
UK, Germany, USA
Austria, USA
USA, Japan
Poland, USA
USA, Indonesia
UK, USA, Iceland
Spain, USA, Hungary, France
USA, UK, Canada
USA, Germany, UK
Italy, USA
USA, Argentina
USA, India
Canada, France, USA
USA, Germany
USA, New Zealand
USA, Ghana
USA, Australia
USA, UK, Canada, Iceland, Norway
USA, China, Japan, Canada, United Arab Emirates
USA, China
Tanzania, USA
USA, Myanmar
USA, Cuba
USA, South Korea
Colombia, USA
Russia, USA, China
Thailand, USA
USA, Russia
USA, UK, Germany
USA, Hong Kong, China
Thailand, USA, Indonesia
USA, Brazil, Canada
Denmark, USA
Nepal
USA, Australia, Spain
Canada, UK, USA
Bahamas, USA
Belgium, USA, Netherlands
Japan, USA
Netherlands, Belgium, UK, USA
USA, Chile, Israel
South Korea, USA, Japan
Ethiopia, USA
Hong Kong, USA, Cambodia, Indonesia, Kenya, Malaysia, Myanmar, Tanzania, Thailand
UK, France, USA
USA, Czech Republic, Bolivia, United Arab Emirates, South Africa
UK, Germany, Canada, Australia, USA
Norway, France, Denmark, USA
Australia, USA, South Africa
USA, Switzerland
Italy, France, USA, Germany, Qatar
USA, Canada, Iraq, United Arab Emirates
USA, China, Hong Kong, Austria
Pakistan, USA
Austria, USA, Australia, Guadeloupe, Italy
South Korea, USA
USA, Chile
USA, Morocco, Spain, UK
Serbia, USA
Bolivia, USA, Argentina, Mexico
USA, Canada, Brazil, France, Philippines, Singapore, UK, Germany
USA, Spain, Peru
Canada, Nigeria, USA
Germany, Belgium, Luxembourg, Ireland, USA
USA, Liberia
USA, Nigeria
USA, UK, Australia
India, UK, USA
Germany, Greece, USA
USA, China, Canada
Canada
China, Germany, USA, Austria, Italy, Canada
Singapore, USA
Spain, USA, Rwanda
USA, Morocco
USA, Spain
Thailand, UK, Germany, France, Malaysia, South Korea, Mexico, USA, Norway
Haiti, USA
Spain, Canada, USA
Portugal, USA
Canada, USA, UK
Singapore, USA, Philippines
Ireland, Canada, UK, USA
Bosnia and Herzegovina, USA
Colombia
USA, UK, Spain, South Korea
Hong Kong, Spain, USA
South Korea, China, USA
Brazil, USA
Hong Kong, USA
USA, UK, France, Hungary, Germany
Japan, Poland, USA
USA, Philippines, UK
USA, Canada, UK, France, Hungary, Belgium
UK, USA, Germany, Denmark, Belgium, Japan
Germany, USA, Poland
USA, Hungary
USA, Australia, China
USA, UK, Morocco
USA, Spain, UK, France
UK, USA, Ireland
Venezuela, USA
UK, USA, Hungary
Ecuador, USA
Puerto Rico, USA
USA, Poland
USA, Hong Kong, Taiwan
Mexico, Italy, USA
Sweden, USA, UK
USA, South Korea, Australia
Sweden, USA
France, USA, United Arab Emirates, Spain, India
USA, Germany, Austria
USA, Thailand
USA, Singapore
USA, Spain, France, UK
Philippines
USA, Colombia, Iran, Kenya, Germany, Romania, Spain, China, UK, Greece, South Africa, Portugal, United Arab Emirates, India, Brazil, Philippines, Italy, Norway, Malaysia, France, Singapore, Indonesia, Bolivia, Bulgaria, Sudan
Canada, New Zealand, USA
UK, Canada, USA
Canada, India, USA
USA, Haiti
USA, Egypt
USA, Bahamas, Canada
Iceland, Switzerland, USA
China, Hong Kong, USA

In [12]:
df.country = df.country.str.lower()

In [13]:
df = df[df['country'].str.contains("usa", na=False)]

In [14]:
total = len(df.country.unique())
unique = df.country.unique()
for i in range (total):
    print(unique[i])

usa
iran, usa
mexico, usa
canada, usa
australia, guyana, usa
australia, canada, usa
israel, usa
canada, usa, india, vietnam
usa, italy
romania, usa, ukraine
china, usa
usa, uk
uk, usa
italy, spain, usa, uk, sweden
usa, bosnia and herzegovina, croatia, italy, switzerland
peru, usa
usa, canada
usa, hong kong
guatemala, usa
germany, usa
switzerland, usa
france, usa
germany, ukraine, usa
spain, usa
usa, france, germany
taiwan, usa
usa, colombia
usa, trinidad and tobago
china, uk, usa
usa, cameroon
usa, mexico
hungary, usa, russia, romania
usa, dominican republic
india, hong kong, indonesia, philippines, singapore, usa, united arab emirates
usa, france, belgium
united arab emirates, usa, switzerland
australia, usa
usa, france
cyprus, greece, usa, serbia
lebanon, usa
germany, india, usa
india, usa
czech republic, usa
france, malta, usa
usa, uk, spain, italy, france
albania, usa
south africa, usa
hong kong, china, usa
czech republic, uk, usa, russia
usa, germany, brazil
uk, australia, usa
south korea, thailand, usa
usa, uk, france
netherlands, usa
new zealand, usa
germany, usa, south africa, norway, italy, hong kong, brazil, australia
usa, turkey, italy, india
mexico, india, usa, argentina, spain
usa, cambodia
uk, germany, usa
austria, usa
usa, japan
poland, usa
usa, indonesia
uk, usa, iceland
spain, usa, hungary, france
usa, uk, canada
usa, germany, uk
italy, usa
usa, argentina
usa, india
canada, france, usa
usa, germany
usa, new zealand
usa, ghana
usa, australia
usa, uk, canada, iceland, norway
usa, china, japan, canada, united arab emirates
usa, china
tanzania, usa
usa, myanmar
usa, cuba
usa, south korea
colombia, usa
russia, usa, china
thailand, usa
usa, russia
usa, uk, germany
usa, hong kong, china
thailand, usa, indonesia
usa, brazil, canada
denmark, usa
usa, australia, spain
canada, uk, usa
bahamas, usa
belgium, usa, netherlands
japan, usa
netherlands, belgium, uk, usa
usa, chile, israel
south korea, usa, japan
ethiopia, usa
hong kong, usa, cambodia, indonesia, kenya, malaysia, myanmar, tanzania, thailand
uk, france, usa
usa, czech republic, bolivia, united arab emirates, south africa
uk, germany, canada, australia, usa
norway, france, denmark, usa
australia, usa, south africa
usa, switzerland
italy, france, usa, germany, qatar
usa, canada, iraq, united arab emirates
usa, china, hong kong, austria
pakistan, usa
austria, usa, australia, guadeloupe, italy
south korea, usa
usa, chile
usa, morocco, spain, uk
serbia, usa
bolivia, usa, argentina, mexico
usa, canada, brazil, france, philippines, singapore, uk, germany
usa, spain, peru
canada, nigeria, usa
germany, belgium, luxembourg, ireland, usa
usa, liberia
usa, nigeria
usa, uk, australia
india, uk, usa
germany, greece, usa
usa, china, canada
china, germany, usa, austria, italy, canada
singapore, usa
spain, usa, rwanda
usa, morocco
usa, spain
thailand, uk, germany, france, malaysia, south korea, mexico, usa, norway
haiti, usa
spain, canada, usa
portugal, usa
canada, usa, uk
singapore, usa, philippines
ireland, canada, uk, usa
bosnia and herzegovina, usa
usa, uk, spain, south korea
hong kong, spain, usa
south korea, china, usa
brazil, usa
hong kong, usa
usa, uk, france, hungary, germany
japan, poland, usa
usa, philippines, uk
usa, canada, uk, france, hungary, belgium
uk, usa, germany, denmark, belgium, japan
germany, usa, poland
usa, hungary
usa, australia, china
usa, uk, morocco
usa, spain, uk, france
uk, usa, ireland
venezuela, usa
uk, usa, hungary
ecuador, usa
puerto rico, usa
usa, poland
usa, hong kong, taiwan
mexico, italy, usa
sweden, usa, uk
usa, south korea, australia
sweden, usa
france, usa, united arab emirates, spain, india
usa, germany, austria
usa, thailand
usa, singapore
usa, spain, france, uk
usa, colombia, iran, kenya, germany, romania, spain, china, uk, greece, south africa, portugal, united arab emirates, india, brazil, philippines, italy, norway, malaysia, france, singapore, indonesia, bolivia, bulgaria, sudan
canada, new zealand, usa
uk, canada, usa
canada, india, usa
usa, haiti
usa, egypt
usa, bahamas, canada
iceland, switzerland, usa
china, hong kong, usa

In [15]:
len(df)

3339

In [16]:
df = df[df.box_office.notnull()]

In [17]:
len(df)

171

In [18]:
# drop min number of non-NA values
df = df.dropna(thresh=7)
df.head(100)

,title_id,title,box_office,country,genre,director,metascore,production,rating,IMDB_rating,rotten_tomatoes_rating,runtime,type,IMDB_votes
35,tt4158624,3 Generations,"$66,371",usa,Drama,Gaby Dellal,47.0,The Weinstein Company,PG-13,5.9,32%,92 min,movie,"5,250"
65,tt2611160,A Beautiful Now,"$1,504",usa,"Comedy, Drama, Music",Daniela Amavia,NaN,Unified Pictures,R,5.7,NaN,90 min,movie,27
129,tt1135989,A Tale of Love and Darkness,"$569,381","israel, usa","Biography, Drama, History, Mystery, Romance, War",Natalie Portman,55.0,Focus World,PG-13,6.0,70%,95 min,movie,"3,185"
138,tt1178665,A Walk in the Woods,"$19,189,413",usa,"Adventure, Biography, Comedy, Drama",Ken Kwapis,51.0,Broad Green Pictures,R,6.3,47%,104 min,movie,"22,701"
220,tt1243974,Aloha,"$15,669,178",usa,"Comedy, Drama, Romance",Cameron Crowe,40.0,Sony Pictures,PG-13,5.4,20%,105 min,movie,"57,595"
230,tt2974918,Alvin and the Chipmunks: The Road Chip,"$66,580,191",usa,"Animation, Adventure, Comedy, Family, Fantasy,...",Walt Becker,33.0,20th Century Fox,PG,5.0,15%,92 min,movie,"15,320"
277,tt3317208,Anesthesia,"$22,386",usa,"Crime, Drama",Tim Blake Nelson,55.0,IFC Films,R,6.1,26%,90 min,movie,"3,992"
295,tt0478970,Ant-Man,"$138,002,223",usa,"Action, Adventure, Comedy, Sci-Fi",Peyton Reed,64.0,Disney/Marvel,PG-13,7.3,83%,117 min,movie,"529,594"
323,tt3774466,Ashby,"$4,631",usa,"Comedy, Crime, Drama, Romance",Tony McNamara,46.0,The Film Arcade,R,6.4,52%,100 min,movie,"13,925"
345,tt2395427,Avengers: Age of Ultron,"$429,113,729",usa,"Action, Adventure, Sci-Fi",Joss Whedon,66.0,Walt Disney Pictures,PG-13,7.3,75%,141 min,movie,"692,489"
404,tt1365050,Beasts of No Nation,"$83,861",usa,"Drama, War",Cary Joji Fukunaga,79.0,Netflix,Not Rated,7.7,92%,137 min,movie,"66,703"
425,tt4630444,Being Charlie,"$11,872",usa,"Drama, Romance",Rob Reiner,47.0,Castle Rock Entertainment,R,6.3,23%,97 min,movie,"3,691"
450,tt2433040,Beyond the Mask,"$1,231,025",usa,"Action, Adventure, Drama, Romance",Chad Burns,NaN,Freestyle Releasing,PG,5.0,17%,103 min,movie,"2,635"
481,tt1355683,Black Mass,"$48,786,443","usa, uk","Biography, Crime, Drama",Scott Cooper,68.0,Warner Bros Pictures,R,6.9,73%,123 min,movie,"159,482"
486,tt2717822,Blackhat,"$5,686,515",usa,"Action, Crime, Thriller",Michael Mann,51.0,Universal Studios,R,5.4,33%,133 min,movie,"49,669"
516,tt3732950,Body,"$2,457",usa,"Crime, Drama, Thriller","Dan Berk, Robert Olsen",49.0,Oscilloscope Pictures,Not Rated,5.2,42%,75 min,movie,"1,595"
553,tt3262990,Brotherly Love,"$46,290",usa,Drama,Jamal Hill,NaN,Freestyle Releasing,R,6.7,NaN,89 min,movie,"1,604"
571,tt3770426,Burning Bodhi,"$3,289",usa,Drama,Matthew McDuffie,NaN,NaN,R,4.8,NaN,93 min,movie,374
579,tt3707106,By the Sea,"$319,968","france, malta, usa","Drama, Romance",Angelina Jolie,44.0,Universal Pictures,R,5.3,35%,122 min,movie,"16,976"
605,tt3268668,Captive,"$1,963,974","mexico, usa","Action, Crime, Drama, Thriller",Jerry Jameson,36.0,Paramount Pictures,PG-13,5.4,27%,97 min,movie,"6,168"
607,tt5197250,Captives,"$1,963,974",usa,"Action, Crime, Drama",Baron Redman,NaN,Paramount Pictures,NaN,NaN,27%,81 min,movie,NaN
614,tt2402927,Carol,"$8,518,148","uk, usa","Drama, Romance",Todd Haynes,95.0,The Weinstein Company,R,7.2,94%,118 min,movie,"105,585"
617,tt3735398,Carter High,"$146,040",usa,"Crime, Drama, Sport",Arthur Muhammad,NaN,Play Now Enterprise,PG-13,5.1,NaN,110 min,movie,454
654,tt4594834,Chi-Raq,"$2,647,378",usa,"Comedy, Crime, Drama, Musical",Spike Lee,77.0,LionsGate Entertainment,R,5.7,82%,127 min,movie,"8,398"
657,tt1014763,Child 44,"$1,314,609","czech republic, uk, usa, russia","Crime, Drama, History, Thriller",Daniel Espinosa,41.0,Summit Entertainment,R,6.5,27%,137 min,movie,"61,747"
664,tt3481000,Chocolate City,"$212,223",usa,Drama,Jean-Claude La Marre,NaN,Freestyle Releasing,R,3.9,NaN,91 min,movie,961
668,tt3703148,Christmas Eve,"$81,992",usa,Comedy,Mitch Davis,24.0,Unstuck,PG,5.0,0%,95 min,movie,"2,209"
677,tt1661199,Cinderella,"$183,327,144","usa, uk","Drama, Family, Fantasy, Romance",Kenneth Branagh,67.0,Walt Disney Pictures,PG,6.9,85%,105 min,movie,"148,539"
715,tt4048168,Coming Through the Rye,"$4,000",usa,Drama,James Steven Sadwith,64.0,Red Hat Films,PG-13,6.3,70%,97 min,movie,768
718,tt3322364,Concussion,"$23,268,108","uk, australia, usa","Biography, Drama, Sport",Peter Landesman,55.0,Sony Pictures,PG-13,7.1,59%,123 min,movie,"80,596"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,tt2908446,Insurgent,"$114,138,208",usa,"Action, Adventure, Sci-Fi, Thriller",Robert Schwentke,42.0,Lionsgate Films,PG-13,6.2,28%,119 min,movie,"205,664"
1465,tt4288636,James White,"$101,368",usa,Drama,Josh Mond,83.0,The Film Arcade,R,7.1,92%,85 min,movie,"5,391"
1466,tt2140037,Jane Got a Gun,"$976,847",usa,"Action, Drama, Western",Gavin O'Connor,49.0,Relativity Media,R,5.9,43%,98 min,movie,"19,613"
1495,tt2446980,Joy,"$42,581,369",usa,Drama,David O. Russell,56.0,20th Century Fox,PG-13,6.6,61%,124 min,movie,"121,476"
1501,tt1617661,Jupiter Ascending,"$43,733,037","usa, australia","Action, Adventure, Sci-Fi","Lana Wachowski, Lilly Wachowski",40.0,Warner Bros. Pictures,PG-13,5.3,27%,127 min,movie,"170,486"
1504,tt0369610,Jurassic World,"$528,757,749",usa,"Action, Adventure, Sci-Fi",Colin Trevorrow,59.0,Universal Pictures,PG-13,7.0,72%,124 min,movie,"553,791"
1541,tt3605418,Knock Knock,"$285,363","usa, chile, israel","Drama, Thriller",Eli Roth,53.0,Lionsgate Premiere,R,4.9,37%,99 min,movie,"72,285"
1543,tt2089721,Know How,"$2,414",usa,"Drama, Musical",Juan Carlos Pineiro Escoriaza,NaN,First Run Features,NaN,7.1,40%,106 min,movie,50
1548,tt4266638,Krisha,"$143,978",usa,Drama,Trey Edward Shults,86.0,A24 Films,R,7.2,95%,83 min,movie,"6,473"
1554,tt2735292,L.A. Slasher,"$2,421","usa, uk","Comedy, Crime, Drama, Horror",Martin Owen,NaN,Archstone Distribution,R,3.5,0%,86 min,movie,709
1562,tt4296800,Ladrones,"$3,058,367","usa, dominican republic",Comedy,Joe Menendez,NaN,Pantelion Films,PG-13,5.0,60%,97 min,movie,244
1585,tt3864024,Lazer Team,"$1,149,878",usa,"Action, Comedy, Sci-Fi",Matt Hullum,42.0,Rooster Teeth Productions,PG-13,5.6,59%,102 min,movie,"8,915"
1591,tt3569230,Legend,"$14,146,549","uk, france, usa","Biography, Crime, Drama, Thriller",Brian Helgeland,55.0,Universal Studios,R,6.9,61%,132 min,movie,"145,181"
1614,tt3442990,Lila & Eve,"$21,806",usa,"Crime, Drama, Mystery, Thriller",Charles Stone III,45.0,Samuel Goldwyn Films,R,5.8,40%,94 min,movie,"7,398"
1621,tt1810683,Little Boy,"$4,902,290","mexico, usa","Drama, History, War",Alejandro Monteverde,30.0,Open Road Films,PG-13,7.4,24%,106 min,movie,"21,366"
1681,tt2884018,Macbeth,"$1,795,802","uk, france, usa","Drama, History, War",Justin Kurzel,71.0,The Weinstein Company,R,6.6,79%,113 min,movie,"50,390"
1684,tt1392190,Mad Max: Fury Road,"$129,483,877","australia, usa, south africa","Action, Adventure, Sci-Fi, Thriller",George Miller,90.0,Warner Bros.,R,8.1,97%,120 min,movie,"809,852"
1688,tt1881002,Maggie,"$136,397","usa, switzerland","Drama, Horror",Henry Hobson,52.0,Lionsgate Films,PG-13,5.6,60%,95 min,movie,"39,991"
1697,tt2378776,Man Up,"$857,215",usa,Comedy,Justin Chon,NaN,LionsGate Entertainment,NaN,5.6,80%,73 min,movie,344
1725,tt3369806,Max,"$26,714,191",usa,"Adventure, Drama, Family, War",Boaz Yakin,47.0,Warner Bros. Pictures,PG,6.7,38%,111 min,movie,"24,590"
1744,tt3262252,Memoria,"$2,164",usa,"Biography, Drama","Vladimir de Fontenay, Nina Ljeti",NaN,RabbitBandini Productions,R,5.0,100%,70 min,movie,449
1746,tt4604496,Men Go to Battle,"$17,950",usa,"Comedy, Drama, History",Zachary Treitz,72.0,Film Movement,NaN,5.2,69%,98 min,movie,275
1776,tt2293640,Minions,"$277,969,969",usa,"Animation, Adventure, Comedy, Family, Sci-Fi","Kyle Balda, Pierre Coffin",56.0,Universal Pictures,PG,6.4,55%,91 min,movie,"200,720"
1787,tt2381249,Mission: Impossible - Rogue Nation,"$154,979,949","usa, china, hong kong, austria","Action, Adventure, Thriller",Christopher McQuarrie,75.0,Paramount Pictures,PG-13,7.4,93%,131 min,movie,"323,066"
1788,tt2349144,Mississippi Grind,"$129,747",usa,"Comedy, Drama","Anna Boden, Ryan Fleck",77.0,A24 and DIRECTV,R,6.4,91%,108 min,movie,"18,063"
1810,tt3045616,Mortdecai,"$6,847,536","uk, usa","Action, Comedy, Crime, Mystery, Romance",David Koepp,27.0,Liongate Films,R,5.5,12%,107 min,movie,"63,025"
1822,tt3168230,Mr. Holmes,"$14,173,994","uk, usa","Drama, Mystery",Bill Condon,67.0,Roadside Attractions,PG,6.9,89%,104 min,movie,"59,208"
1824,tt2091935,Mr. Right,"$25,369",usa,"Action, Comedy, Romance",Paco Cabezas,52.0,Circle of Confusion,R,6.3,44%,95 min,movie,"44,078"
1825,tt3812348,Mr. Right,"$25,369",usa,Comedy,Roger Melvin,NaN,Circle of Confusion,Not Rated,3.0,44%,79 min,movie,273
1833,tt3719896,My All-American,"$1,365,000",usa,"Biography, Drama, Sport",Angelo Pizzo,34.0,Aviron,PG,7.1,32%,118 min,movie,"5,288"

In [19]:
len(df)

171

In [20]:
df.to_csv('../data/cleaned_2013_data.csv', index=False)

In [21]:
train = df[['title', 'box_office', 'country', 'genre', 'production', 'rating', 'runtime']]
train.head()

,title,box_office,country,genre,production,rating,runtime
6,Dean,"$248,849",usa,"Comedy, Drama, Romance",CBS Films,PG-13,94 min
9,10 Cloverfield Lane,"$59,481,553",usa,"Drama, Horror, Mystery, Sci-Fi, Thriller",Bad Robot Productions,PG-13,103 min
13,13 Hours,"$37,978,162","malta, morocco, usa","Action, Drama, History, Thriller, War",Paramount Pictures,R,144 min
24,20th Century Women,"$5,663,854",usa,"Comedy, Drama",A24 Films,R,119 min
32,3 Weeks in Yerevan,"$29,245",usa,Comedy,Wet Paint Production,NaN,NaN

In [22]:
train = train.reset_index(drop = True)
train.head()

,title,box_office,country,genre,production,rating,runtime
0,Dean,"$248,849",usa,"Comedy, Drama, Romance",CBS Films,PG-13,94 min
1,10 Cloverfield Lane,"$59,481,553",usa,"Drama, Horror, Mystery, Sci-Fi, Thriller",Bad Robot Productions,PG-13,103 min
2,13 Hours,"$37,978,162","malta, morocco, usa","Action, Drama, History, Thriller, War",Paramount Pictures,R,144 min
3,20th Century Women,"$5,663,854",usa,"Comedy, Drama",A24 Films,R,119 min
4,3 Weeks in Yerevan,"$29,245",usa,Comedy,Wet Paint Production,NaN,NaN

In [23]:
train['country'] = train['country'].str.count(',')
train['country'] = train['country'] + 1
train.head()

,title,box_office,country,genre,production,rating,runtime
0,Dean,"$248,849",1,"Comedy, Drama, Romance",CBS Films,PG-13,94 min
1,10 Cloverfield Lane,"$59,481,553",1,"Drama, Horror, Mystery, Sci-Fi, Thriller",Bad Robot Productions,PG-13,103 min
2,13 Hours,"$37,978,162",3,"Action, Drama, History, Thriller, War",Paramount Pictures,R,144 min
3,20th Century Women,"$5,663,854",1,"Comedy, Drama",A24 Films,R,119 min
4,3 Weeks in Yerevan,"$29,245",1,Comedy,Wet Paint Production,NaN,NaN

In [24]:
train['genre'] = train['genre'].str.count(',')
train['genre'] = train['genre'] + 1
train.head()

,title,box_office,country,genre,production,rating,runtime
0,Dean,"$248,849",1,3,CBS Films,PG-13,94 min
1,10 Cloverfield Lane,"$59,481,553",1,5,Bad Robot Productions,PG-13,103 min
2,13 Hours,"$37,978,162",3,5,Paramount Pictures,R,144 min
3,20th Century Women,"$5,663,854",1,2,A24 Films,R,119 min
4,3 Weeks in Yerevan,"$29,245",1,1,Wet Paint Production,NaN,NaN

In [25]:
train['rating'].value_counts()

R            89
PG-13        88
PG           29
Not Rated    13
Unrated       9
TV-MA         4
Name: rating, dtype: int64

In [26]:
train['rating'] = train['rating'].str.replace('Not Rated', 'Unrated')
train.head()

,title,box_office,country,genre,production,rating,runtime
0,Dean,"$248,849",1,3,CBS Films,PG-13,94 min
1,10 Cloverfield Lane,"$59,481,553",1,5,Bad Robot Productions,PG-13,103 min
2,13 Hours,"$37,978,162",3,5,Paramount Pictures,R,144 min
3,20th Century Women,"$5,663,854",1,2,A24 Films,R,119 min
4,3 Weeks in Yerevan,"$29,245",1,1,Wet Paint Production,NaN,NaN

In [27]:
train['rating'] = train['rating'].fillna('Unrated')

In [28]:
train['rating'].value_counts()

R          89
PG-13      88
Unrated    31
PG         29
TV-MA       4
Name: rating, dtype: int64

In [29]:
train['runtime'] = train['runtime'].astype(str)

In [30]:
train['runtime'] = train['runtime'].apply(lambda x: x.replace(' min',''))
train.head()

,title,box_office,country,genre,production,rating,runtime
0,Dean,"$248,849",1,3,CBS Films,PG-13,94
1,10 Cloverfield Lane,"$59,481,553",1,5,Bad Robot Productions,PG-13,103
2,13 Hours,"$37,978,162",3,5,Paramount Pictures,R,144
3,20th Century Women,"$5,663,854",1,2,A24 Films,R,119
4,3 Weeks in Yerevan,"$29,245",1,1,Wet Paint Production,Unrated,nan

In [31]:
train['runtime'] = train['runtime'].apply(lambda x: x.replace('nan','0'))
train.head()

,title,box_office,country,genre,production,rating,runtime
0,Dean,"$248,849",1,3,CBS Films,PG-13,94
1,10 Cloverfield Lane,"$59,481,553",1,5,Bad Robot Productions,PG-13,103
2,13 Hours,"$37,978,162",3,5,Paramount Pictures,R,144
3,20th Century Women,"$5,663,854",1,2,A24 Films,R,119
4,3 Weeks in Yerevan,"$29,245",1,1,Wet Paint Production,Unrated,0

In [32]:
train['runtime'] = train['runtime'].astype(int)

In [33]:
train.production.value_counts()

Warner Bros. Pictures               13
20th Century Fox                    12
Paramount Pictures                  11
Walt Disney Pictures                 9
Sony Pictures                        9
Universal Pictures                   9
Open Road Films                      8
Lionsgate                            5
Sony Pictures Classics               5
The Orchard                          3
BH Tilt                              3
Focus Features                       3
Parts and Labor                      3
Fox Searchlight Pictures             2
Likely Story                         2
CBS Films                            2
STX Entertainment                    2
Monterey Media                       2
Gravitas Ventures                    2
The Weinstein Company                2
Lionsgate Films                      2
NEON                                 2
DreamWorks Animation                 2
Lakeshore Entertainment              2
IFC Films                            2
Summit Entertainment                 2
A24 Films                            2
Killer Films                         2
Amazon Studios                       1
Relativity Studios                   1
                                    ..
Big Beach Films                      1
Vertigo Entertainment                1
Focus World                          1
DJ Films                             1
Netflix                              1
Walt Disney Pictures/PIXAR           1
Dreamworks Pictures                  1
Beachside Films                      1
Miramax and Roadside Attractions     1
Electric Entertainment               1
Animal Kingdom                       1
Scott Free Films                     1
Ghost House Pictures                 1
BH Tilt/WWE Studios                  1
Electric Chinoland                   1
21 Laps Entertainment                1
Roadside Attractions                 1
Gramercy Pictures                    1
Sneaky Sneaky Films                  1
Rook Films                           1
Broad Green Pictures                 1
Electric City Entertainment          1
Ombra Films                          1
Riverstone Pictures                  1
Blackmrkt                            1
Siegal Entertainment                 1
Street Justice Films                 1
RatPac-Dune Entertainment            1
Keep Your Head                       1
Illumination Entertainment           1
Name: production, Length: 137, dtype: int64

In [34]:
train['production'] = train['production'].fillna('NaN')

In [35]:
train['box_office'] = train['box_office'].apply(lambda x: x.replace('$',''))
train.head()

,title,box_office,country,genre,production,rating,runtime
0,Dean,"248,849",1,3,CBS Films,PG-13,94
1,10 Cloverfield Lane,"59,481,553",1,5,Bad Robot Productions,PG-13,103
2,13 Hours,"37,978,162",3,5,Paramount Pictures,R,144
3,20th Century Women,"5,663,854",1,2,A24 Films,R,119
4,3 Weeks in Yerevan,"29,245",1,1,Wet Paint Production,Unrated,0

In [36]:
train['box_office'] = train['box_office'].apply(lambda x: x.replace(',',''))
train.head()

,title,box_office,country,genre,production,rating,runtime
0,Dean,248849,1,3,CBS Films,PG-13,94
1,10 Cloverfield Lane,59481553,1,5,Bad Robot Productions,PG-13,103
2,13 Hours,37978162,3,5,Paramount Pictures,R,144
3,20th Century Women,5663854,1,2,A24 Films,R,119
4,3 Weeks in Yerevan,29245,1,1,Wet Paint Production,Unrated,0

In [37]:
train['box_office'] = train['box_office'].astype(int)
train.head()

,title,box_office,country,genre,production,rating,runtime
0,Dean,248849,1,3,CBS Films,PG-13,94
1,10 Cloverfield Lane,59481553,1,5,Bad Robot Productions,PG-13,103
2,13 Hours,37978162,3,5,Paramount Pictures,R,144
3,20th Century Women,5663854,1,2,A24 Films,R,119
4,3 Weeks in Yerevan,29245,1,1,Wet Paint Production,Unrated,0

In [38]:
train.dtypes

title         object
box_office     int32
country        int64
genre          int64
production    object
rating        object
runtime        int32
dtype: object

In [39]:
train.dtypes

title         object
box_office     int32
country        int64
genre          int64
production    object
rating        object
runtime        int32
dtype: object

In [40]:
train['year'] = 2013

In [41]:
train.to_csv('../data/train_data_2013.csv', index=False)

In [42]:
train = train.sort_values(by=['box_office'], ascending=False)

In [43]:
train.head()

,title,box_office,country,genre,production,rating,runtime,year
160,Rogue One: A Star Wars Story,532171696,1,3,Walt Disney Pictures,PG-13,133,2016
68,Finding Dory,486292984,1,4,Walt Disney Pictures/PIXAR,PG,97,2016
43,Captain America: Civil War,408080554,1,3,Walt Disney Pictures,PG-13,147,2016
223,The Secret Life of Pets,368305960,3,4,Universal Pictures,PG,87,2016
212,The Jungle Book,363995937,2,4,Walt Disney Pictures,PG,106,2016
240,Zootopia,341264012,1,6,Walt Disney Animation Studios,PG,108,2016
56,Deadpool,328674489,1,4,20th Century Fox,R,108,2016
178,Suicide Squad,325021779,1,4,Warner Bros. Pictures,PG-13,123,2016
27,Batman v Superman: Dawn of Justice,293792936,1,3,Warner Bros. Pictures,PG-13,151,2016
167,Sing,270322940,2,4,Illumination Entertainment,PG,108,2016
125,Moana,248752120,1,6,Walt Disney Pictures,PG,107,2016
66,Fantastic Beasts and Where to Find Them,234018657,2,3,Warner Bros. Pictures,PG-13,132,2016
60,Doctor Strange,232630718,1,4,Walt Disney Pictures,PG-13,115,2016
84,Hidden Figures,169385416,1,3,20th Century Fox,PG,127,2016
95,Jason Bourne,162162120,2,2,Universal,PG-13,123,2016
176,Star Trek Beyond,158804470,4,4,Paramount Pictures,PG-13,122,2016
228,Trolls,153694574,1,6,DreamWorks Animation,PG,92,2016
105,La La Land,151058124,2,5,Liongate Films,PG-13,128,2016
175,Split,138120085,2,2,Universal Pictures,PG-13,117,2016
238,X-Men: Apocalypse,135729385,1,3,20th Century Fox,PG-13,144,2016
73,Ghostbusters,128344089,2,4,Sony Pictures,PG-13,116,2016
103,Kung Fu Panda 3,128341070,2,6,DreamWorks Animation,PG,95,2016
46,Central Intelligence,127380061,2,3,Warner Bros. Pictures,PG-13,107,2016
215,The Legend of Tarzan,126585313,3,5,Lionsgate Pictures,PG-13,110,2016
179,Sully,125065700,1,2,Warner Bros.,PG-13,96,2016
23,Bad Moms,113217955,1,1,Block Entertainment,R,100,2016
19,The Angry Birds Movie,107506776,2,5,Sony Pictures,PG,97,2016
89,Independence Day: Resurgence,103137295,1,3,20th Century Fox,PG-13,120,2016
196,The Conjuring 2,102461593,3,3,Warner Bros. Pictures,R,134,2016
21,Arrival,100501349,3,4,21 Laps Entertainment,PG-13,116,2016
...,...,...,...,...,...,...,...,...
166,Simple Creature,22766,1,2,NaN,Unrated,92,2016
226,The Transfiguration,21926,1,2,Transfiguration Prods.,Unrated,97,2016
237,Wild Oats,21554,2,4,The Weinstein Company,PG-13,86,2016
137,"No Pay, Nudity",20017,1,2,A Day in the Life Films,R,92,2016
209,The Homeless Billionaire,19771,1,1,NaN,Unrated,88,2016
45,Carrie Pilby,19025,1,2,The Orchard,Unrated,98,2016
156,Radio Dreams,18642,1,1,Butimar Productions,Unrated,93,2016
213,The Land,17958,1,1,Low Spark Films,R,104,2016
39,Brave New Jersey,14105,1,1,Gravitas Ventures,TV-MA,86,2016
182,Term Life,13040,1,3,Focus World,R,93,2016
15,Always Shine,11891,1,4,Little Teeth Pictures,Unrated,85,2016
152,Porto,11823,4,2,Salem Street Entertainment,R,76,2016
111,Lovesong,10545,1,2,Strand Releasing,Unrated,84,2016
97,Junction 48,9083,3,6,The Orchard,Unrated,95,2016
31,Beta Test,8966,1,3,Mirror Images LTD.,Unrated,88,2016
72,Ghost Team,8069,1,2,Tandem Pictures,PG-13,83,2016
193,The Charnel House,6332,1,2,Siegal Entertainment,R,90,2016
69,Frank & Lola,5747,1,4,Parts and Labor,Unrated,88,2016
86,Icaros: A Vision,5510,2,1,Factory 25,Unrated,91,2016
70,From Nowhere,5408,1,1,No Place for Films,Unrated,89,2016
6,A Beginner's Guide to Snuff,5204,1,3,Indican Pictures,Unrated,87,2016
36,Blue Jay,5159,1,2,Duplass Brothers,Unrated,80,2016
192,The Channel,4214,1,3,NaN,Unrated,93,2016
124,Miss Stevens,3858,1,2,Beachside Films,Unrated,86,2016
214,The Last Film Festival,3506,1,1,NaN,R,90,2016
134,My Father Die,3229,1,2,KnightMarcher,Unrated,90,2016
204,The Girl on the Train,2874,1,1,Monterey Media,R,80,2016
157,Range 15,1044,1,3,Street Justice Films,TV-MA,89,2016
144,Officer Downe,734,1,3,Blackmrkt,R,88,2016
162,Satanic,205,1,1,Marvista Entertainment,R,85,2016

In [44]:
train.iloc[:20, 1]=1

In [45]:
train.head()

,title,box_office,country,genre,production,rating,runtime,year
160,Rogue One: A Star Wars Story,1,1,3,Walt Disney Pictures,PG-13,133,2016
68,Finding Dory,1,1,4,Walt Disney Pictures/PIXAR,PG,97,2016
43,Captain America: Civil War,1,1,3,Walt Disney Pictures,PG-13,147,2016
223,The Secret Life of Pets,1,3,4,Universal Pictures,PG,87,2016
212,The Jungle Book,1,2,4,Walt Disney Pictures,PG,106,2016
240,Zootopia,1,1,6,Walt Disney Animation Studios,PG,108,2016
56,Deadpool,1,1,4,20th Century Fox,R,108,2016
178,Suicide Squad,1,1,4,Warner Bros. Pictures,PG-13,123,2016
27,Batman v Superman: Dawn of Justice,1,1,3,Warner Bros. Pictures,PG-13,151,2016
167,Sing,1,2,4,Illumination Entertainment,PG,108,2016
125,Moana,1,1,6,Walt Disney Pictures,PG,107,2016
66,Fantastic Beasts and Where to Find Them,1,2,3,Warner Bros. Pictures,PG-13,132,2016
60,Doctor Strange,1,1,4,Walt Disney Pictures,PG-13,115,2016
84,Hidden Figures,1,1,3,20th Century Fox,PG,127,2016
95,Jason Bourne,1,2,2,Universal,PG-13,123,2016
176,Star Trek Beyond,1,4,4,Paramount Pictures,PG-13,122,2016
228,Trolls,1,1,6,DreamWorks Animation,PG,92,2016
105,La La Land,1,2,5,Liongate Films,PG-13,128,2016
175,Split,1,2,2,Universal Pictures,PG-13,117,2016
238,X-Men: Apocalypse,1,1,3,20th Century Fox,PG-13,144,2016
73,Ghostbusters,128344089,2,4,Sony Pictures,PG-13,116,2016
103,Kung Fu Panda 3,128341070,2,6,DreamWorks Animation,PG,95,2016
46,Central Intelligence,127380061,2,3,Warner Bros. Pictures,PG-13,107,2016
215,The Legend of Tarzan,126585313,3,5,Lionsgate Pictures,PG-13,110,2016
179,Sully,125065700,1,2,Warner Bros.,PG-13,96,2016
23,Bad Moms,113217955,1,1,Block Entertainment,R,100,2016
19,The Angry Birds Movie,107506776,2,5,Sony Pictures,PG,97,2016
89,Independence Day: Resurgence,103137295,1,3,20th Century Fox,PG-13,120,2016
196,The Conjuring 2,102461593,3,3,Warner Bros. Pictures,R,134,2016
21,Arrival,100501349,3,4,21 Laps Entertainment,PG-13,116,2016
...,...,...,...,...,...,...,...,...
166,Simple Creature,22766,1,2,NaN,Unrated,92,2016
226,The Transfiguration,21926,1,2,Transfiguration Prods.,Unrated,97,2016
237,Wild Oats,21554,2,4,The Weinstein Company,PG-13,86,2016
137,"No Pay, Nudity",20017,1,2,A Day in the Life Films,R,92,2016
209,The Homeless Billionaire,19771,1,1,NaN,Unrated,88,2016
45,Carrie Pilby,19025,1,2,The Orchard,Unrated,98,2016
156,Radio Dreams,18642,1,1,Butimar Productions,Unrated,93,2016
213,The Land,17958,1,1,Low Spark Films,R,104,2016
39,Brave New Jersey,14105,1,1,Gravitas Ventures,TV-MA,86,2016
182,Term Life,13040,1,3,Focus World,R,93,2016
15,Always Shine,11891,1,4,Little Teeth Pictures,Unrated,85,2016
152,Porto,11823,4,2,Salem Street Entertainment,R,76,2016
111,Lovesong,10545,1,2,Strand Releasing,Unrated,84,2016
97,Junction 48,9083,3,6,The Orchard,Unrated,95,2016
31,Beta Test,8966,1,3,Mirror Images LTD.,Unrated,88,2016
72,Ghost Team,8069,1,2,Tandem Pictures,PG-13,83,2016
193,The Charnel House,6332,1,2,Siegal Entertainment,R,90,2016
69,Frank & Lola,5747,1,4,Parts and Labor,Unrated,88,2016
86,Icaros: A Vision,5510,2,1,Factory 25,Unrated,91,2016
70,From Nowhere,5408,1,1,No Place for Films,Unrated,89,2016
6,A Beginner's Guide to Snuff,5204,1,3,Indican Pictures,Unrated,87,2016
36,Blue Jay,5159,1,2,Duplass Brothers,Unrated,80,2016
192,The Channel,4214,1,3,NaN,Unrated,93,2016
124,Miss Stevens,3858,1,2,Beachside Films,Unrated,86,2016
214,The Last Film Festival,3506,1,1,NaN,R,90,2016
134,My Father Die,3229,1,2,KnightMarcher,Unrated,90,2016
204,The Girl on the Train,2874,1,1,Monterey Media,R,80,2016
157,Range 15,1044,1,3,Street Justice Films,TV-MA,89,2016
144,Officer Downe,734,1,3,Blackmrkt,R,88,2016
162,Satanic,205,1,1,Marvista Entertainment,R,85,2016

In [48]:
train.iloc[20:,1]=0

In [49]:
train.head()

,title,box_office,country,genre,production,rating,runtime,year
160,Rogue One: A Star Wars Story,1,1,3,Walt Disney Pictures,PG-13,133,2016
68,Finding Dory,1,1,4,Walt Disney Pictures/PIXAR,PG,97,2016
43,Captain America: Civil War,1,1,3,Walt Disney Pictures,PG-13,147,2016
223,The Secret Life of Pets,1,3,4,Universal Pictures,PG,87,2016
212,The Jungle Book,1,2,4,Walt Disney Pictures,PG,106,2016
240,Zootopia,1,1,6,Walt Disney Animation Studios,PG,108,2016
56,Deadpool,1,1,4,20th Century Fox,R,108,2016
178,Suicide Squad,1,1,4,Warner Bros. Pictures,PG-13,123,2016
27,Batman v Superman: Dawn of Justice,1,1,3,Warner Bros. Pictures,PG-13,151,2016
167,Sing,1,2,4,Illumination Entertainment,PG,108,2016
125,Moana,1,1,6,Walt Disney Pictures,PG,107,2016
66,Fantastic Beasts and Where to Find Them,1,2,3,Warner Bros. Pictures,PG-13,132,2016
60,Doctor Strange,1,1,4,Walt Disney Pictures,PG-13,115,2016
84,Hidden Figures,1,1,3,20th Century Fox,PG,127,2016
95,Jason Bourne,1,2,2,Universal,PG-13,123,2016
176,Star Trek Beyond,1,4,4,Paramount Pictures,PG-13,122,2016
228,Trolls,1,1,6,DreamWorks Animation,PG,92,2016
105,La La Land,1,2,5,Liongate Films,PG-13,128,2016
175,Split,1,2,2,Universal Pictures,PG-13,117,2016
238,X-Men: Apocalypse,1,1,3,20th Century Fox,PG-13,144,2016
73,Ghostbusters,0,2,4,Sony Pictures,PG-13,116,2016
103,Kung Fu Panda 3,0,2,6,DreamWorks Animation,PG,95,2016
46,Central Intelligence,0,2,3,Warner Bros. Pictures,PG-13,107,2016
215,The Legend of Tarzan,0,3,5,Lionsgate Pictures,PG-13,110,2016
179,Sully,0,1,2,Warner Bros.,PG-13,96,2016
23,Bad Moms,0,1,1,Block Entertainment,R,100,2016
19,The Angry Birds Movie,0,2,5,Sony Pictures,PG,97,2016
89,Independence Day: Resurgence,0,1,3,20th Century Fox,PG-13,120,2016
196,The Conjuring 2,0,3,3,Warner Bros. Pictures,R,134,2016
21,Arrival,0,3,4,21 Laps Entertainment,PG-13,116,2016
...,...,...,...,...,...,...,...,...
166,Simple Creature,0,1,2,NaN,Unrated,92,2016
226,The Transfiguration,0,1,2,Transfiguration Prods.,Unrated,97,2016
237,Wild Oats,0,2,4,The Weinstein Company,PG-13,86,2016
137,"No Pay, Nudity",0,1,2,A Day in the Life Films,R,92,2016
209,The Homeless Billionaire,0,1,1,NaN,Unrated,88,2016
45,Carrie Pilby,0,1,2,The Orchard,Unrated,98,2016
156,Radio Dreams,0,1,1,Butimar Productions,Unrated,93,2016
213,The Land,0,1,1,Low Spark Films,R,104,2016
39,Brave New Jersey,0,1,1,Gravitas Ventures,TV-MA,86,2016
182,Term Life,0,1,3,Focus World,R,93,2016
15,Always Shine,0,1,4,Little Teeth Pictures,Unrated,85,2016
152,Porto,0,4,2,Salem Street Entertainment,R,76,2016
111,Lovesong,0,1,2,Strand Releasing,Unrated,84,2016
97,Junction 48,0,3,6,The Orchard,Unrated,95,2016
31,Beta Test,0,1,3,Mirror Images LTD.,Unrated,88,2016
72,Ghost Team,0,1,2,Tandem Pictures,PG-13,83,2016
193,The Charnel House,0,1,2,Siegal Entertainment,R,90,2016
69,Frank & Lola,0,1,4,Parts and Labor,Unrated,88,2016
86,Icaros: A Vision,0,2,1,Factory 25,Unrated,91,2016
70,From Nowhere,0,1,1,No Place for Films,Unrated,89,2016
6,A Beginner's Guide to Snuff,0,1,3,Indican Pictures,Unrated,87,2016
36,Blue Jay,0,1,2,Duplass Brothers,Unrated,80,2016
192,The Channel,0,1,3,NaN,Unrated,93,2016
124,Miss Stevens,0,1,2,Beachside Films,Unrated,86,2016
214,The Last Film Festival,0,1,1,NaN,R,90,2016
134,My Father Die,0,1,2,KnightMarcher,Unrated,90,2016
204,The Girl on the Train,0,1,1,Monterey Media,R,80,2016
157,Range 15,0,1,3,Street Justice Films,TV-MA,89,2016
144,Officer Downe,0,1,3,Blackmrkt,R,88,2016
162,Satanic,0,1,1,Marvista Entertainment,R,85,2016

In [50]:
train.to_csv('../data/train.log_data_2013.csv', index=False)