In [1]:
import pandas as pd

In [2]:
batch_1 = pd.read_csv('../data/2017_data_batch_1.csv')
batch_2 = pd.read_csv('../data/2017_data_batch_2.csv')
batch_3 = pd.read_csv('../data/2017_data_batch_3.csv')
batch_4 = pd.read_csv('../data/2017_data_batch_4.csv')

In [3]:
len(batch_1)

959

In [4]:
len(batch_2)

949

In [5]:
len(batch_3)

936

In [6]:
len(batch_4)

805

In [7]:
df = pd.DataFrame()

In [8]:
df = pd.concat([batch_1, batch_2, batch_3, batch_4], ignore_index=True)

In [9]:
len(df)

3649

In [10]:
df.head(100)

,title_id,title,box_office,country,genre,director,metascore,production,rating,IMDB_rating,rotten_tomatoes_rating,runtime,type,IMDB_votes
0,tt6856592,#Captured,NaN,USA,Thriller,Joe Homokay,NaN,NaN,NaN,6.1,NaN,81 min,movie,"1,101"
1,tt6479626,#CoEdConfessions,NaN,USA,"Comedy, Romance","William Cardoza, Guillermo Gomez, Rachael Hada...",NaN,NaN,NaN,NaN,NaN,61 min,movie,NaN
2,tt6119504,#REALITYHIGH,NaN,USA,"Comedy, Drama, Romance",Fernando Lebrija,NaN,NaN,TV-14,5.2,NaN,99 min,movie,"4,800"
3,tt5654204,#Slaughterhouse,NaN,USA,"Action, Horror",Dino Maglaris,NaN,NaN,NaN,7.5,NaN,NaN,movie,24
4,tt6046566,#humbled,NaN,USA,NaN,Russell Max Simon,NaN,NaN,NaN,NaN,NaN,76 min,movie,NaN
5,tt6359426,#murderchallenge,NaN,USA,Horror,Michael Bilinski,NaN,NaN,UNRATED,NaN,NaN,NaN,movie,NaN
6,tt6608094,&,NaN,USA,NaN,Cedric van Eenoo,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
7,tt0326716,5-25-77,NaN,USA,"Comedy, Drama",Patrick Read Johnson,NaN,NaN,NaN,6.1,NaN,113 min,movie,299
8,tt4685428,1 Buck,NaN,USA,"Drama, Thriller",Fabien Dufils,NaN,Gravitas Ventures,TV-MA,6.0,NaN,90 min,movie,"2,304"
9,tt2184233,1 Mile to You,NaN,USA,"Drama, Romance, Sport",Leif Tilden,NaN,Gravitas Ventures,TV-14,6.3,NaN,104 min,movie,"2,000"
10,tt6235650,10/31,NaN,USA,Horror,"Brett DeJager, Rocky Gray, Zane Hershberger, J...",NaN,NaN,NaN,6.6,NaN,NaN,movie,93
11,tt6105714,100 Blocks,NaN,USA,Drama,Diaunte Thompson,NaN,NaN,NaN,8.5,NaN,87 min,movie,11
12,tt5760674,1040 Not So EZ,NaN,USA,Drama,David Nguyen,NaN,NaN,NaN,NaN,NaN,90 min,movie,NaN
13,tt5143226,12 Feet Deep,NaN,USA,"Horror, Thriller",Matt Eskandari,NaN,NaN,Not Rated,5.6,NaN,85 min,movie,"11,102"
14,tt5544754,12 Pound Balls,NaN,USA,Comedy,Zachary Madson,NaN,NaN,TV-MA,4.0,NaN,80 min,movie,137
15,tt3396208,12 Round Gun,NaN,USA,"Drama, Sport",Sam Upton,NaN,NaN,TV-MA,4.6,NaN,92 min,movie,172
16,tt5193216,13 Chambers,NaN,USA,"Drama, Fantasy, Horror","Jessica Aceti, Megumi Arai, Lindy Boustedt, Cl...",NaN,NaN,NaN,NaN,NaN,73 min,movie,NaN
17,tt6544454,13 Minuteman,NaN,USA,"Action, Drama",Chaz Feldman,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
18,tt7385874,18 Days,NaN,USA,NaN,Rafael Ragland,NaN,NaN,NaN,NaN,NaN,92 min,movie,NaN
19,tt6214928,1922,NaN,USA,"Crime, Drama, Horror, Mystery, Thriller",Zak Hilditch,70.0,Netflix,TV-MA,6.3,90%,102 min,movie,"42,125"
20,tt5748356,1948,NaN,USA,NaN,Ken Sibanda,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
21,tt7732524,1993,NaN,USA,Horror,Elle Millie,NaN,NaN,NaN,3.8,NaN,73 min,movie,5
22,tt7003386,2 Lanes,NaN,USA,Mystery,Villa Mane,NaN,NaN,NaN,3.9,NaN,56 min,movie,10
23,tt3752610,2 Years of Love,NaN,USA,"Comedy, Romance",Thadd Turner,NaN,NaN,UNRATED,4.3,NaN,88 min,movie,111
24,tt5475468,20 Weeks,NaN,USA,"Drama, Romance",Leena Pendharkar,NaN,Uncork&#39;d Entertainment,NaN,5.0,NaN,90 min,movie,137
25,tt4762592,200 Degrees,NaN,USA,Thriller,Giorgio Serafini,NaN,NaN,TV-14,4.4,NaN,91 min,movie,447
26,tt6864870,200 Miles,NaN,USA,Drama,Sam Bathrick,NaN,NaN,NaN,7.8,NaN,50 min,movie,6
27,tt5157616,2016,NaN,USA,Horror,Gary Anthony Sturgis,NaN,NaN,NaN,7.1,NaN,NaN,movie,36
28,tt6361966,2016 Dancing Dolls a Christmas Story,NaN,USA,Family,NaN,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
29,tt6528348,21st Century America,NaN,USA,Drama,NaN,NaN,NaN,NaN,NaN,NaN,90 min,movie,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,tt6802896,A Ciambra,NaN,"Italy, Brazil, Germany, France, Sweden, USA","Crime, Drama",Jonas Carpignano,70.0,IFC Films,Unrated,6.9,89%,118 min,movie,"1,816"
71,tt4943620,A Closer Walk with Thee,NaN,USA,"Drama, Horror","John C. Clark, Brie Williams",NaN,NaN,NaN,3.9,NaN,90 min,movie,126
72,tt5704912,A Cowgirl's Story,NaN,USA,Family,Timothy Armstrong,NaN,Rodeo Films,PG,5.3,NaN,98 min,movie,434
73,tt2636186,A Crack in Everything,NaN,USA,Drama,Varushka Franceschi,NaN,NaN,NaN,5.3,NaN,90 min,movie,13
74,tt5922124,A Crooked Somebody,NaN,USA,"Drama, Thriller",Trevor White,74.0,NaN,R,6.2,NaN,102 min,movie,625
75,tt4385852,A Curry on an American Plate,NaN,USA,Comedy,San Banarje,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
76,tt3499358,A Demon Within,NaN,USA,"Drama, Horror, Romance","Ayush Banker, Justin LaReau",NaN,NaN,TV-14,3.3,NaN,91 min,movie,558
77,tt6982394,A Descent to Grace,NaN,USA,NaN,Daniel Kesselman,NaN,NaN,NaN,8.6,NaN,78 min,movie,7
78,tt6700004,A Devil's Wind,NaN,USA,Horror,Bill Zebub,NaN,NaN,UNRATED,NaN,NaN,NaN,movie,NaN
79,tt4955992,The Different Sun,NaN,USA,Drama,Reed Tang,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
80,tt1753383,A Dog's Purpose,"$64,304,940","USA, India","Adventure, Comedy, Drama, Family, Fantasy",Lasse Hallström,43.0,Amblin Entertainment,PG,7.1,35%,100 min,movie,"58,759"
81,tt6315010,A Doggone Hollywood,NaN,USA,Family,Jim Wynorski,NaN,NaN,TV-PG,3.8,NaN,84 min,movie,18
82,tt6364638,Winter Wedding,NaN,USA,Romance,Jake Helgren,NaN,NaN,Unrated,5.0,NaN,90 min,movie,290
83,tt4817008,A Fancy Piece of Homicide,NaN,USA,"Crime, Mystery, Thriller",Joseph Varhola,NaN,NaN,NaN,5.0,NaN,100 min,movie,51
84,tt4151002,A Feast of Man,NaN,USA,"Comedy, Drama",Caroline Golum,NaN,NaN,Not Rated,4.8,NaN,82 min,movie,11
85,tt8096860,A Feminist Christmas Carol,NaN,USA,Comedy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
86,tt8070082,A First Time for Everything,NaN,USA,Drama,Reginald Flemming,NaN,NaN,NaN,NaN,NaN,49 min,movie,NaN
87,tt5460552,A Flush of Hearts,NaN,USA,"Crime, Drama",Matt Mudd,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
88,tt7476494,A Frozen Christmas 2,NaN,USA,Animation,Arleen Tamaray,NaN,NaN,TV-Y7,2.8,NaN,70 min,movie,20
89,tt6265828,A Ghost Story,"$1,594,798",USA,"Drama, Fantasy, Romance",David Lowery,84.0,Ideaman Studios,R,6.8,91%,92 min,movie,"50,702"
90,tt5126730,Haunted,NaN,USA,"Mystery, Thriller",Mahum Jamal,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
91,tt5228262,A Happening of Monumental Proportions,NaN,"USA, UK","Comedy, Drama",Judy Greer,35.0,NaN,R,4.6,NaN,81 min,movie,554
92,tt6151110,A Journey Through Pines,NaN,USA,Drama,Jimmy Andrews,NaN,NaN,NaN,6.1,NaN,115 min,movie,10
93,tt3583390,A Lack of Furniture,NaN,USA,Romance,Eric Neal Allred,NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
94,tt5766746,A Long Time for Lovers,NaN,USA,"Comedy, Drama",David McElfresh,NaN,NaN,NaN,NaN,NaN,75 min,movie,NaN
95,tt3760544,A Loss of Shadows,NaN,USA,Thriller,"Jack Walker-Pearson, Patrick Scherrer",NaN,NaN,NaN,NaN,NaN,NaN,movie,NaN
96,tt2959606,A Lotus 'Til Reckoning,NaN,USA,Drama,David McElfresh,NaN,NaN,NaN,8.9,NaN,111 min,movie,8
97,tt7262820,A Lover Betrayed,NaN,USA,Thriller,Jeff Hare,NaN,NaN,Not Rated,5.8,NaN,90 min,movie,130
98,tt7690328,A Meowy Christmas,NaN,USA,"Comedy, Family",Steve Rudzinski,NaN,NaN,NaN,5.7,NaN,60 min,movie,35
99,tt4286432,A Mermaid's Tale,NaN,USA,"Adventure, Drama, Family",Dustin Rikert,NaN,"Lighthouse Pictures, Inc.",G,4.8,NaN,92 min,movie,329

In [11]:
df = df[df.box_office.notnull()]

In [12]:
len(df)

195

In [13]:
df.to_csv('../data/cleaned_2017_data.csv', index=False)

In [15]:
test = df[['title', 'box_office', 'country', 'genre', 'rating', 'runtime', 'production']]

In [16]:
test

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,"$44,305,642","UK, USA","Adventure, Drama, Horror, Thriller",PG-13,89 min,Entertainment Studios Motion Pictures
56,7 Witches,"$31,100",USA,"Horror, Thriller",Not Rated,75 min,Indican Pictures
63,A Bad Moms Christmas,"$72,080,547","USA, China",Comedy,R,104 min,STXfilms
80,A Dog's Purpose,"$64,304,940","USA, India","Adventure, Comedy, Drama, Family, Fantasy",PG,100 min,Amblin Entertainment
89,A Ghost Story,"$1,594,798",USA,"Drama, Fantasy, Romance",R,92 min,Ideaman Studios
108,A Question of Faith,"$2,507,723",USA,Drama,PG,104 min,Pure Flix Entertainment
181,Alien: Covenant,"$74,255,908","USA, UK","Horror, Sci-Fi, Thriller",R,122 min,20th Century Fox
188,All Eyez on Me,"$44,892,121",USA,"Biography, Drama, Music",R,139 min,SUMMIT/CODEBLACK FILMS/LIONSGATE
196,All Saints,"$5,750,509",USA,Drama,PG,108 min,Sony Pictures / Affirm Films
202,All the Money in the World,"$20,153,135","USA, Italy, UK","Biography, Crime, Drama, Mystery, Thriller",R,132 min,TriStar Pictures
220,American Assassin,"$34,449,582",USA,"Action, Thriller",R,112 min,Lionsgate and CBS Films
227,American Made,"$51,071,805","USA, Japan, Colombia","Action, Biography, Comedy, Crime",R,115 min,Universal Pictures
233,Americons,"$14,404",USA,"Action, Biography, Crime, Drama",R,88 min,Archstone Distribution
267,Annabelle: Creation,"$101,788,793",USA,"Horror, Mystery, Thriller",R,109 min,New Line Cinema
305,Atomic Blonde,"$51,536,935","Germany, Sweden, USA, Hungary","Action, Mystery, Thriller",R,115 min,Focus Features
329,Baby Driver,"$107,770,367","UK, USA","Action, Crime, Drama, Music, Thriller",R,113 min,Sony Pictures
337,Bad Grandmas,"$14,450",USA,"Action, Comedy, Crime",NaN,92 min,Parade Deck Films
347,Band Aid,"$245,140",USA,"Comedy, Drama, Music, Romance",R,91 min,IFC Films
360,Battle of the Sexes,"$12,552,907","UK, USA","Biography, Comedy, Drama, Sport",PG-13,121 min,Fox Searchlight Pictures
363,Baywatch,"$58,009,442","UK, China, USA","Action, Comedy, Crime",R,116 min,Paramount Pictures
367,Beach Rats,"$457,847",USA,Drama,R,98 min,NEON
370,Beatriz at Dinner,"$7,115,001",USA,"Comedy, Drama",R,82 min,Roadside Attractions
375,Beauty and the Beast,"$503,974,884",USA,"Family, Fantasy, Musical, Romance",PG,129 min,Walt Disney Pictures
381,Before I Fall,"$12,230,741",USA,"Drama, Fantasy, Mystery",PG-13,98 min,Open Road Films
440,Blade Runner 2049,"$91,800,042","USA, UK, Hungary, Canada, Spain","Action, Drama, Mystery, Sci-Fi, Thriller",R,164 min,Warner Bros. Pictures
444,Blind,"$11,700",USA,"Drama, Romance",R,98 min,Vertical Entertainment
505,Brad's Status,"$2,029,594",USA,"Comedy, Drama, Music",R,102 min,Amazon Studios
521,Brigsby Bear,"$529,426","USA, China","Comedy, Drama",PG-13,97 min,Sony Pictures Classics
560,CHIPS,"$18,591,819",USA,"Action, Comedy, Crime",R,100 min,Warner Bros. Pictures
591,Captain Underpants: The First Epic Movie,"$73,895,861","USA, Canada, France, UK, India","Animation, Action, Comedy, Family",PG,89 min,20th Century Fox
...,...,...,...,...,...,...,...
3292,The Zookeeper's Wife,"$17,407,536","Czech Republic, UK, USA","Biography, Drama, History, War",PG-13,127 min,Focus Features
3316,Thor: Ragnarok,"$314,971,245",USA,"Action, Adventure, Comedy, Fantasy, Sci-Fi",PG-13,130 min,Walt Disney Pictures
3318,"Three Billboards Outside Ebbing, Missouri","$52,000,189","UK, USA","Comedy, Crime, Drama",R,115 min,Fox Searchlight Pictures
3329,Til Death Do Us Part,"$2,640,645",USA,"Short, Drama",NaN,NaN,Novus Content
3330,Til Death Do Us Part,"$2,640,645",USA,Thriller,PG-13,101 min,Novus Content
3332,"Tim Timmerman, Hope of America","$97,505",USA,"Comedy, Romance",PG-13,94 min,Purdie Distribution
3347,Tom of Finland,"$323,048","Finland, Sweden, Denmark, Germany, Iceland, USA","Biography, Drama",Not Rated,117 min,Kino Lorber
3360,Tragedy Girls,"$58,016",USA,"Comedy, Crime, Horror",R,98 min,Gunpowder &amp; Sky
3363,Transformers: The Last Knight,"$130,104,634","USA, China, Canada","Action, Adventure, Sci-Fi",PG-13,154 min,Paramount Pictures
3386,Tulip Fever,"$2,399,374","UK, USA","Drama, History, Romance",R,105 min,The Weinstein Company
3397,Boo 2! A Madea Halloween,"$46,649,659",USA,"Comedy, Drama, Horror",PG-13,101 min,Lionsgate
3419,Unforgettable,"$11,274,490",USA,"Drama, Thriller",R,100 min,Warner Bros. Pictures
3435,Valerian and the City of a Thousand Planets,"$40,442,321","France, China, Belgium, Germany, United Arab E...","Action, Adventure, Fantasy, Sci-Fi",PG-13,137 min,EuropaCorp / STXfilms
3436,Valley of Bones,"$168,387",USA,"Crime, Thriller, Western",R,90 min,Bad Medicine Films
3446,Vengeance: A Love Story,"$4,526",USA,"Action, Crime, Drama, Thriller",TV-MA,99 min,Patriot Pictures
3454,Victoria & Abdul,"$21,667,320","UK, USA","Biography, Drama, History",PG-13,111 min,Focus Features
3483,Walking Out,"$101,947",USA,"Adventure, Drama, Mystery, Thriller",PG-13,95 min,IFC Films
3489,War for the Planet of the Apes,"$146,872,826","USA, Canada, New Zealand","Action, Adventure, Drama, Sci-Fi, Thriller",PG-13,140 min,20th Century Fox
3507,"We Love You, Sally Carmichael!","$28,500",USA,Comedy,PG,84 min,GO Films
3517,Weightless,"$421,856",USA,Drama,NaN,NaN,Broad Green Pictures
3572,Wilson,"$652,997",USA,"Comedy, Drama",R,94 min,Fox Searchlight
3574,Wind River,"$33,782,714","UK, Canada, USA","Crime, Drama, Mystery, Thriller",R,107 min,The Weinstein Company
3577,Wish Upon,"$14,301,001","USA, Canada","Drama, Fantasy, Horror, Mystery, Thriller",PG-13,90 min,Broad Green Pictures
3586,Wonder,"$132,090,170","USA, Hong Kong","Drama, Family",PG,113 min,Lionsgate
3589,Wonder Woman,"$412,400,625","USA, China, Hong Kong","Action, Adventure, Fantasy, Sci-Fi, War",PG-13,141 min,Warner Bros. Pictures
3590,Wonderstruck,"$976,561",USA,"Drama, Mystery",PG,116 min,Amazon Studios
3591,Woodshock,"$41,126",USA,"Drama, Thriller",R,100 min,A24 Films
3597,XX,"$30,611","Canada, USA",Horror,R,80 min,XYZ Films
3599,The Devotion of Suspect X,"$686,435","USA, China","Crime, Thriller",Unrated,112 min,China Lion Film Distribution
3647,xXx: Return of Xander Cage,"$44,850,317","China, Canada, USA","Action, Adventure, Thriller",PG-13,107 min,Paramount Pictures

In [17]:
test['country'] = test['country'].str.count(',')
test['country'] = test['country']+1
test.head()

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,"$44,305,642",2,"Adventure, Drama, Horror, Thriller",PG-13,89 min,Entertainment Studios Motion Pictures
56,7 Witches,"$31,100",1,"Horror, Thriller",Not Rated,75 min,Indican Pictures
63,A Bad Moms Christmas,"$72,080,547",2,Comedy,R,104 min,STXfilms
80,A Dog's Purpose,"$64,304,940",2,"Adventure, Comedy, Drama, Family, Fantasy",PG,100 min,Amblin Entertainment
89,A Ghost Story,"$1,594,798",1,"Drama, Fantasy, Romance",R,92 min,Ideaman Studios

In [18]:
test['genre']= test['genre'].str.count(',')
test['genre']= test['genre']+1
test.head()

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,"$44,305,642",2,4,PG-13,89 min,Entertainment Studios Motion Pictures
56,7 Witches,"$31,100",1,2,Not Rated,75 min,Indican Pictures
63,A Bad Moms Christmas,"$72,080,547",2,1,R,104 min,STXfilms
80,A Dog's Purpose,"$64,304,940",2,5,PG,100 min,Amblin Entertainment
89,A Ghost Story,"$1,594,798",1,3,R,92 min,Ideaman Studios

In [19]:
test['rating'].value_counts()

R            84
PG-13        64
PG           25
Not Rated     7
Unrated       2
TV-MA         2
G             1
Name: rating, dtype: int64

In [20]:
test['rating']= test['rating'].str.replace('Not Rated', 'Unrated')
test.head()

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,"$44,305,642",2,4,PG-13,89 min,Entertainment Studios Motion Pictures
56,7 Witches,"$31,100",1,2,Unrated,75 min,Indican Pictures
63,A Bad Moms Christmas,"$72,080,547",2,1,R,104 min,STXfilms
80,A Dog's Purpose,"$64,304,940",2,5,PG,100 min,Amblin Entertainment
89,A Ghost Story,"$1,594,798",1,3,R,92 min,Ideaman Studios

In [21]:
test['rating']=test['rating'].fillna('Unrated')
test.head()

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,"$44,305,642",2,4,PG-13,89 min,Entertainment Studios Motion Pictures
56,7 Witches,"$31,100",1,2,Unrated,75 min,Indican Pictures
63,A Bad Moms Christmas,"$72,080,547",2,1,R,104 min,STXfilms
80,A Dog's Purpose,"$64,304,940",2,5,PG,100 min,Amblin Entertainment
89,A Ghost Story,"$1,594,798",1,3,R,92 min,Ideaman Studios

In [22]:
test['runtime'] = test['runtime'].astype(str)

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
test['runtime'] = test['runtime'].apply(lambda x: x.replace(' min', ''))
test.head()

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,"$44,305,642",2,4,PG-13,89,Entertainment Studios Motion Pictures
56,7 Witches,"$31,100",1,2,Unrated,75,Indican Pictures
63,A Bad Moms Christmas,"$72,080,547",2,1,R,104,STXfilms
80,A Dog's Purpose,"$64,304,940",2,5,PG,100,Amblin Entertainment
89,A Ghost Story,"$1,594,798",1,3,R,92,Ideaman Studios

In [24]:
test['runtime'] = test['runtime'].apply(lambda x: x.replace('nan', '0'))
test.head()

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,"$44,305,642",2,4,PG-13,89,Entertainment Studios Motion Pictures
56,7 Witches,"$31,100",1,2,Unrated,75,Indican Pictures
63,A Bad Moms Christmas,"$72,080,547",2,1,R,104,STXfilms
80,A Dog's Purpose,"$64,304,940",2,5,PG,100,Amblin Entertainment
89,A Ghost Story,"$1,594,798",1,3,R,92,Ideaman Studios

In [25]:
test['runtime']= test['runtime'].astype(int)

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [26]:
test['production']= test['production'].fillna('NaN')
test.head()

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,"$44,305,642",2,4,PG-13,89,Entertainment Studios Motion Pictures
56,7 Witches,"$31,100",1,2,Unrated,75,Indican Pictures
63,A Bad Moms Christmas,"$72,080,547",2,1,R,104,STXfilms
80,A Dog's Purpose,"$64,304,940",2,5,PG,100,Amblin Entertainment
89,A Ghost Story,"$1,594,798",1,3,R,92,Ideaman Studios

In [27]:
test['box_office'] = test['box_office'].apply(lambda x: x.replace('$', ''))
test.head()

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,"44,305,642",2,4,PG-13,89,Entertainment Studios Motion Pictures
56,7 Witches,"31,100",1,2,Unrated,75,Indican Pictures
63,A Bad Moms Christmas,"72,080,547",2,1,R,104,STXfilms
80,A Dog's Purpose,"64,304,940",2,5,PG,100,Amblin Entertainment
89,A Ghost Story,"1,594,798",1,3,R,92,Ideaman Studios

In [28]:
test['box_office'] = test['box_office'].apply(lambda x: x.replace(',', ''))
test.head()

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,title,box_office,country,genre,rating,runtime,production
42,47 Meters Down,44305642,2,4,PG-13,89,Entertainment Studios Motion Pictures
56,7 Witches,31100,1,2,Unrated,75,Indican Pictures
63,A Bad Moms Christmas,72080547,2,1,R,104,STXfilms
80,A Dog's Purpose,64304940,2,5,PG,100,Amblin Entertainment
89,A Ghost Story,1594798,1,3,R,92,Ideaman Studios

In [29]:
test['box_office']= test['box_office'].astype(int)

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
test.dtypes

title         object
box_office     int32
country        int64
genre          int64
rating        object
runtime        int32
production    object
dtype: object

In [31]:
test['year'] = 2017

C:\Users\johna\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
test.to_csv('../data/test_data_2017.csv', index=False)

In [33]:
test = test.sort_values(by=['box_office'], ascending=False)

In [34]:
test.head()

,title,box_office,country,genre,rating,runtime,production,year
2573,Star Wars: Episode VIII - The Last Jedi,619117636,1,4,PG-13,152,Walt Disney Pictures,2017
375,Beauty and the Beast,503974884,1,4,PG,129,Walt Disney Pictures,2017
3589,Wonder Woman,412400625,3,5,PG-13,141,Warner Bros. Pictures,2017
1556,Jumanji: Welcome to the Jungle,393201353,6,4,PG-13,119,Columbia Pictures,2017
1269,Guardians of the Galaxy Vol. 2,389804217,1,4,PG-13,136,Walt Disney Pictures,2017

In [35]:
test.iloc[:20, 1]=1

In [36]:
test.head()

,title,box_office,country,genre,rating,runtime,production,year
2573,Star Wars: Episode VIII - The Last Jedi,1,1,4,PG-13,152,Walt Disney Pictures,2017
375,Beauty and the Beast,1,1,4,PG,129,Walt Disney Pictures,2017
3589,Wonder Woman,1,3,5,PG-13,141,Warner Bros. Pictures,2017
1556,Jumanji: Welcome to the Jungle,1,6,4,PG-13,119,Columbia Pictures,2017
1269,Guardians of the Galaxy Vol. 2,1,1,4,PG-13,136,Walt Disney Pictures,2017

In [37]:
test.iloc[20:,1]=0

In [38]:
test.head()

,title,box_office,country,genre,rating,runtime,production,year
2573,Star Wars: Episode VIII - The Last Jedi,1,1,4,PG-13,152,Walt Disney Pictures,2017
375,Beauty and the Beast,1,1,4,PG,129,Walt Disney Pictures,2017
3589,Wonder Woman,1,3,5,PG-13,141,Warner Bros. Pictures,2017
1556,Jumanji: Welcome to the Jungle,1,6,4,PG-13,119,Columbia Pictures,2017
1269,Guardians of the Galaxy Vol. 2,1,1,4,PG-13,136,Walt Disney Pictures,2017

In [39]:
test.to_csv('../data/test.log_data_2017.csv', index=False)

In [40]:
test.production.value_counts()

Warner Bros. Pictures                    15
20th Century Fox                         11
Paramount Pictures                        8
Universal Pictures                        8
Focus Features                            7
Fox Searchlight Pictures                  6
Walt Disney Pictures                      6
Lionsgate                                 6
Sony Pictures                             5
Open Road Films                           5
Magnolia Pictures                         4
Columbia Pictures                         4
IFC Films                                 4
Amazon Studios                            4
FilmRise                                  4
A24                                       3
A24 Films                                 3
NEON                                      3
The Orchard                               3
Broad Green Pictures                      3
Universal Studios                         3
EuropaCorp / STXfilms                     2
Novus Content                             2
Summit Entertainment                      2
Gunpowder &amp; Sky                       2
Pure Flix Entertainment                   2
Sony Pictures Animation                   2
Entertainment Studios Motion Pictures     2
Aviron Pictures                           2
Annapurna Pictures                        2
                                         ..
Vertical Entertainment                    1
Good Deed Entertainment                   1
Bleecker Street Media                     1
Pure Flix                                 1
Kino Lorber                               1
Bad Medicine Films                        1
Paladin                                   1
XYZ Films                                 1
Pantelion Films                           1
Cinelou Films                             1
Fox Searchlight                           1
Archstone Distribution                    1
Paramount Pictures / Pure Flix            1
RiverRain Productions                     1
Disney/Pixar                              1
GO Films                                  1
Amazon Studios and IFC Films              1
Amazon Studios/Roadside Attractions       1
Screen Media Films                        1
Skydance Films                            1
Amblin Entertainment                      1
China Lion Film Distribution              1
Bleecker Street                           1
Harlem Film Company                       1
Sony Pictures Classics                    1
Maven Pictures                            1
TriStar Pictures                          1
Hannover House                            1
SUMMIT/CODEBLACK FILMS/LIONSGATE          1
Samuel Goldwyn Films                      1
Name: production, Length: 87, dtype: int64